import { ProductDetailProps } from "@/types/componentTypes";
import { NextResponse } from "next/server";

const productDetails : ProductDetailProps[] = [
    {
        id: "id1",
        name: "Gucci duffle bag",
        image: "bag",
        desc: "A premium Gucci duffle bag, perfect for travel and everyday use.",
        price: "960",
        category: "Gaming",
    },
    {
        id: "id2",
        name: "RGB liquid CPU Cooler",
        image: "CPUCooler",
        desc: "High-performance CPU cooler with vibrant RGB lighting.",
        price: "1960",
        category: "Gaming",
    },
    {
        id: "id3",
        name: "GP11 Shooter USB Gamepad",
        image: "Gamepad",
        desc: "Ergonomic USB gamepad for smooth and responsive gaming.",
        price: "550",
        category: "Gaming",
    },
    {
        id: "id4",
        name: "Quilted Satin Jacket",
        image: "jacket",
        desc: "Stylish quilted satin jacket for a sleek and modern look.",
        price: "750",
        category: "Mens Wear",
    },
    {
        id: "id5",
        name: "ASUS FHD Gaming Laptop",
        image: "laptop",
        desc: "Powerful ASUS laptop with Full HD display for gaming.",
        price: "960",
        category: "Gaming",
    },
    {
        id: "id6",
        name: "IPS LCD Gaming Monitor",
        image: "GamingMonitor",
        desc: "Immersive IPS LCD monitor designed for high-speed gaming.",
        price: "1160",
        category: "Gaming",
    },
    {
        id: "id7",
        name: "AK-900 Wired Keyboard",
        image: "keyboard",
        desc: "Durable wired keyboard with a comfortable typing experience.",
        price: "960",
        category: "Gaming",
    },
    {
        id: "id8",
        name: "HAVIT HV-G92 Gamepad",
        image: "gameRemote",
        desc: "Affordable and reliable gamepad for casual gaming.",
        price: "120",
        category: "Gaming",
    },
    {
        id: "id9",
        name: "S-Series Comfort Chair",
        image: "chair",
        desc: "Ergonomic chair designed for long hours of comfort.",
        price: "375",
        category: "Furniture",
    },
    {
        id: "id10",
        name: "The north coat",
        image: "northCoat",
        desc: "Classic and cozy coat for staying warm in winter.",
        price: "260",
        category: "Mens Wear",
    },
    {
        id: "id11",
        name: "Small BookSelf",
        image: "BookSelf",
        desc: "Compact bookshelf to organize your books and decor.",
        price: "360",
        category: "Furniture",
    },
    {
        id: "id12",
        name: "Breed Dry Dog Food",
        image: "DogFood",
        desc: "Nutritious dry food tailored for all dog breeds.",
        price: "260",
        category: "Animals Food",
    },
    {
        id: "id13",
        name: "CANON EOS DSLR Camera",
        image: "DSLRCamera",
        desc: "Capture stunning photos with this high-quality DSLR camera.",
        price: "360",
        category: "Camera",
    },
    {
        id: "id14",
        name: "Curology Product Set",
        image: "productSet",
        desc: "Complete skincare set for clear and healthy skin.",
        price: "500",
        category: "Skin Care Products",
    },
    {
        id: "id15",
        name: "Kids Electric Car",
        image: "KidsElectricCar",
        desc: "Fun and safe electric car for kids to enjoy driving.",
        price: "960",
        category: "Toys",
    },
    {
        id: "id16",
        name: "Jr. Zoom Soccer Cleats",
        image: "Shoes",
        desc: "Lightweight soccer cleats for young players.",
        price: "960",
        category: "Shoes",
    },
];

export async function GET() {
    return NextResponse.json(productDetails, { status: 200 });
}